# Generated by Django 3.2.7 on 2022-01-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
