# Generated by Django 3.2.7 on 2022-01-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220102_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='promocode',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
