# Generated by Django 3.2.7 on 2022-01-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
    ]
