# Generated by Django 3.2.7 on 2022-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20220105_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='imageurl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
