# Generated by Django 3.2.7 on 2022-01-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rent_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='imageurl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
